---
apiVersion: identity.vault.upbound.io/v1alpha1
kind: OidcScope
metadata:
  name: email
  namespace: vault
spec:
  forProvider:
    name: email
    template: |
      {
        "email": {{identity.entity.metadata.email}}
      }   
---
apiVersion: identity.vault.upbound.io/v1alpha1
kind: OidcScope
metadata:
  name: groups
  namespace: vault
spec:
  forProvider:
    name: groups
    template: |
      {
        "groups": {{identity.entity.groups.names}}
      }   
---
apiVersion: identity.vault.upbound.io/v1alpha1
kind: OidcScope
metadata:
  name: user
  namespace: vault
spec:
  forProvider:
    name: user
    template: |
      {
          "username": {{identity.entity.name}},
          "contact": 
          {
              "email": {{identity.entity.metadata.email}},
              "phone_number": {{identity.entity.metadata.phone_number}}
          }
      }
---
apiVersion: vault.kundun.dev/v1alpha1
kind: OIDCClaim
metadata:
  name: idp
  namespace: vault
spec:
  compositionSelector:
    matchLabels:
      provider: vault
  id: idp-oidc
  redirectUris: [ "https://auth.contoso.com:8443/oauth2/laza/authorization-code-callback" ]
  scopesSupported: [ "email", "user", "groups" ]
