apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-kundun-wildcard-selfsigned
  namespace: gateway 
spec:
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  dnsNames:
    - kundun.dev
    - "*.kundun.dev"
  secretName: cert-kundun-wildcard-selfsigned

  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048

  duration: 2160h # 90d
  renewBefore: 360h # 15d

  isCA: false
  usages:
    - server auth
    - client auth

  subject:
    organizations:
      - cert-manager
