#vault write auth/kubernetes/config \
#    kubernetes_host="https://kubernetes.default.svc:443"

# vault write auth/kubernetes/role/issuer \
#     bound_service_account_names=issuer \
#     bound_service_account_namespaces=vault \
#     policies=pki \
#     ttl=20m

apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: vault-issuer
  namespace: gateway
spec:
  vault:
    server: http://vault-0.vault-dev-internal.vault:8200
    path: pki/sign/kundun-dev
    auth:
      kubernetes:
        mountPath: /v1/auth/kubernetes
        role: issuer
        secretRef:
          name: issuer-token
          key: token