apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-kv-minio
  namespace: minio
spec:
  type: kv-v2
  mount: internal
  path: minio/creds
  destination:
    name: admin-credentials
    create: true
  vaultAuthRef: static-auth