storageClass:
  - name: proxmox-csi
    cache: writethrough
    fstype: ext4
    reclaimPolicy: Delete
    ssd: true
    storage: local-lvm
    mountOptions:
      - noatime
#FIXME: Change to Retain for live system
#    reclaimPolicy: Retain
