---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: kuberneteses.vault.kundun.dev
spec:
  group: vault.kundun.dev
  names:
    kind: Kubernetes
    plural: kuberneteses
  claimNames:
    kind: KubernetesClaim
    plural: kubernetesclaims
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              id:
                type: string
                description: Kubernetes Auth ID
              policy:
                type: object
                properties:
                  name:
                    type: string
                    description: Policy name
                  paths:
                    type: string
                    description: Policy ACL paths
                required: [ name, paths ]
              kubernetesHost:
                type: string
                description: Kubernetes Internal API URL
              role:
                type: object
                properties:
                  name:
                    type: string
                  boundServiceAccountNames:
                    type: array
                    items:
                      type: string
                    minItems: 1
                  boundServiceAccountNamespaces:
                    type: array
                    items:
                      type: string
                    minItems: 1
                  tokenPolicies: 
                    type: array
                    items:
                      type: string
                    minItems: 1
                  tokenTtl:
                    type: number
                required: [ name, boundServiceAccountNames, boundServiceAccountNamespaces, tokenPolicies, tokenTtl ]
            required: [ id, kubernetesHost, policy, role ]
          status:
            type: object
            properties:
              mountAccessor:
                type: string