---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: oidc
  labels:
    provider: vault
spec:
  compositeTypeRef:
    apiVersion: vault.kundun.dev/v1alpha1
    kind: OIDC
  mode: Pipeline
  pipeline:
  - functionRef:
      name: function-patch-and-transform
    step: patch-and-transform
    input:
      apiVersion: pt.fn.crossplane.io/v1beta1
      kind: Resources
      patchSets:
      - name: metadata
        patches:
        - type: FromCompositeFieldPath
          fromFieldPath: metadata.annotations
          toFieldPath: metadata.annotations
        - type: FromCompositeFieldPath
          fromFieldPath: spec.id
          toFieldPath: metadata.name
      resources:
      - name: key
        base:
          apiVersion: identity.vault.upbound.io/v1alpha1
          kind: OidcKey
          spec:
            forProvider:
              allowedClientIds:  [ "*" ]
              rotationPeriod: 3600
              verificationTtl: 7200
              algorithm: RS256
        patches:
        - type: PatchSet
          patchSetName: metadata
        - type: FromCompositeFieldPath
          fromFieldPath: spec.id
          toFieldPath: spec.forProvider.name
      - name: client
        base:
          apiVersion: identity.vault.upbound.io/v1alpha1
          kind: OidcClient
          spec:
            forProvider:
              idTokenTtl: 1800
              accessTokenTtl: 3600
              assignments: [ "allow_all" ]
        patches:
        - type: PatchSet
          patchSetName: metadata
        - type: FromCompositeFieldPath
          fromFieldPath: spec.id
          toFieldPath: spec.forProvider.name
        - type: FromCompositeFieldPath
          fromFieldPath: spec.id
          toFieldPath: spec.forProvider.key
        - type: FromCompositeFieldPath
          fromFieldPath: spec.redirectUris
          toFieldPath: spec.forProvider.redirectUris
        - type: FromCompositeFieldPath
          fromFieldPath: spec.redirectUris
          toFieldPath: spec.forProvider.redirectUris
        - type: ToCompositeFieldPath
          fromFieldPath: status.atProvider.clientId
          toFieldPath: status.clientId
      - name: provider
        base:
          apiVersion: identity.vault.upbound.io/v1alpha1
          kind: OidcProvider
        patches:
        - type: PatchSet
          patchSetName: metadata
        - type: FromCompositeFieldPath
          fromFieldPath: spec.id
          toFieldPath: spec.forProvider.name
        - type: FromCompositeFieldPath
          fromFieldPath: spec.scopesSupported
          toFieldPath: spec.forProvider.scopesSupported
        - type: FromCompositeFieldPath
          fromFieldPath: status.clientId
          toFieldPath: spec.forProvider.allowedClientIds
          transforms:
            - type: string
              string:
                type: Format
                fmt: '[ "%s" ]'
            - type: convert
              convert:
                toType: array
                format: json
