apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cnpg-single
  namespace: cnpg
spec:
  storage:
    pvcTemplate:
      accessModes:
      - ReadWriteOnce
      storageClassName: local-path
    size: 1G