apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-creator
  namespace: vault
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: default-secret-creator
  namespace: vault
subjects:
- kind: ServiceAccount
  name: default
  namespace: vault
roleRef:
  kind: Role
  name: secret-creator
  apiGroup: rbac.authorization.k8s.io