global:
  namespace: vault
server:
  dev:
    enabled: true
  injector:
    enabled: false
  # extraEnvironmentVars is a list of extra environment variables to set with the stateful set. These could be
  # used to include variables required for auto-unseal.
  extraSecretEnvironmentVars:
    - envName: VAULT_TOKEN
      secretName: vault-transit-secret
      secretKey: root_token
#      valueFrom: /vault/userconfig/vault-transit-secret/root_token
#    VAULT_CACERT: /vault/userconfig/tls-ca/ca.crt

  # extraVolumes is a list of extra volumes to mount. These will be exposed
  # to Vault in the path `/vault/userconfig/<name>/`.
  # extraVolumes:
  #   - type: secret
  #     name: vault-transit-secret
