apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cnpg-single
  namespace: cnpg-system
spec:
  instances: 1
  affinity:
    nodeSelector:
      topology.kubernetes.io/zone: noa
  managed:
    services:
      disabledDefaultServices: ["ro", "r"]
  storage:
    size: 1G
    pvcTemplate:
      storageClassName: proxmox-csi
      accessModes:
        - ReadWriteOnce
  # bootstrap:
  #   initdb:
  #     database: wikijs
  #     owner: wikijs
  #     secret:
  #       name: single-wikijs-app