apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-kv-minio
  namespace: cnpg-system
spec:
  type: kv-v2
  mount: internal
  path: cnpg/creds
  destination:
    name: admin-credentials
    create: true
  vaultAuthRef: static-auth