apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: static-auth
  namespace: cnpg-system
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: internal-app
    serviceAccount: default
